

//pagination
export let LAST_PAGE_REACHED = "[GROUPS]_LAST_PAGE_REACHED";
export let FIRST_PAGE_REACHED = "[GROUPS]_FIRST_PAGE_REACHED";
export const NEXT_PAGE = "[GROUPS]_NEXT_PAGE";
export const PREVIOUS_PAGE = "[GROUPS]_PREVIOUS";

export const SET_PAGE = "[GROUPS]_SET_PAGE";
export const INVALIDATE_ALL = '[GROUPS]_INVALIDATE_ALL'

export const SELECT_ITEM = '[GROUPS]_SELECT_ITEM'
//loading
export const FETCHING = '[GROUPS]_FETCHING'
export const UPLOADING = '[GROUPS]_UPLOADING';
//many
export const RECEIVED_MANY = '[GROUPS]_RECEIVED'
export const FETCH_ERROR = '[GROUPS]_FETCH_ERROR'
// single
export const SINGLE_RECEIVED = '[GROUPS]_SINGLE_RECEIVED'
//upload
export const UPLOAD_SUCCESS = '[GROUPS]_UPLOAD_SUCCESS';
export const UPLOAD_ERROR = '[GROUPS]_UPLOAD_ERROR';
//update
export const UPDATE_SUCCESS = '[GROUPS]_UPDATE_SUCCESS';
export const UPDATE_ERROR = '[GROUPS]_UPDATE_ERROR';
//delete
export const DELETE_SUCCESS = '[GROUPS]_DELETE_SUCCESS';
export const DELETE_ERROR = '[GROUPS]_DELETE_ERROR';
