

//pagination
export let LAST_PAGE_REACHED = "[GENRES]_LAST_PAGE_REACHED";
export let FIRST_PAGE_REACHED = "[GENRES]_FIRST_PAGE_REACHED";
export const NEXT_PAGE = "[GENRES]_NEXT_PAGE";
export const PREVIOUS_PAGE = "[GENRES]_PREVIOUS";

export const SET_PAGE = "[GENRES]_SET_PAGE";
export const INVALIDATE_ALL = '[GENRES]_INVALIDATE_ALL'

export const SELECT_ITEM = '[GENRES]_SELECT_ITEM'
//loading
export const FETCHING = '[GENRES]_FETCHING'
export const UPLOADING = '[GENRES]_UPLOADING';
//many
export const RECEIVED_MANY = '[GENRES]_RECEIVED'
export const FETCH_ERROR = '[GENRES]_FETCH_ERROR'
// single
export const SINGLE_RECEIVED = '[GENRES]_SINGLE_RECEIVED'
//upload
export const UPLOAD_SUCCESS = '[GENRES]_UPLOAD_SUCCESS';
export const UPLOAD_ERROR = '[GENRES]_UPLOAD_ERROR';
//update
export const UPDATE_SUCCESS = '[GENRES]_UPDATE_SUCCESS';
export const UPDATE_ERROR = '[GENRES]_UPDATE_ERROR';
//delete
export const DELETE_SUCCESS = '[GENRES]_DELETE_SUCCESS';
export const DELETE_ERROR = '[GENRES]_DELETE_ERROR';
