//pagination
export let LAST_PAGE_REACHED = "[CATEGORIES]_LAST_PAGE_REACHED";
export let FIRST_PAGE_REACHED = "[CATEGORIES]_FIRST_PAGE_REACHED";
export const NEXT_PAGE = "[CATEGORIES]_NEXT_PAGE";
export const PREVIOUS_PAGE = "[CATEGORIES]_PREVIOUS";

export const SET_PAGE = "[CATEGORIES]_SET_PAGE";
export const INVALIDATE_ALL = '[CATEGORIES]_INVALIDATE_ALL'

export const SELECT_ITEM = '[CATEGORIES]_SELECT_ITEM'
//loading
export const FETCHING = '[CATEGORIES]_FETCHING'
export const UPLOADING = '[CATEGORIES]_UPLOADING';
//many
export const RECEIVED_MANY = '[CATEGORIES]_RECEIVED'
export const FETCH_ERROR = '[CATEGORIES]_FETCH_ERROR'
// single
export const SINGLE_RECEIVED = '[CATEGORIES]_SINGLE_RECEIVED'
//upload
export const UPLOAD_SUCCESS = '[CATEGORIES]_UPLOAD_SUCCESS';
export const UPLOAD_ERROR = '[CATEGORIES]_UPLOAD_ERROR';
//update
export const UPDATE_SUCCESS = '[CATEGORIES]_UPDATE_SUCCESS';
export const UPDATE_ERROR = '[CATEGORIES]_UPDATE_ERROR';
//delete
export const DELETE_SUCCESS = '[CATEGORIES]_DELETE_SUCCESS';
export const DELETE_ERROR = '[CATEGORIES]_DELETE_ERROR';
